### ISSUE TITLE
Bootstrap 3 fails to compile when MinifyOutput is true

### ISSUE THREAD

**Issue by Sense545** [dotless/dotless#346]
Bootstrap 3 fails to compile when DotlessConfiguration's MinifyOutput is true.

    // Bootstrap 3 - dropdowns.less:153
    .pull-right > .dropdown-menu {
      right: 0;
      left: auto;
    }

Should be usable as a mixin and be usable like so:

    // Bootstrap 3 - dropdowns.less:186
    @media (min-width: @grid-float-breakpoint) {
      .navbar-right {
        .dropdown-menu {
          .pull-right > .dropdown-menu();
        }
      }
    }

And should produce the following output:

    @media (min-width: 768px) {
      .navbar-right .dropdown-menu {
        right: 0;
        left: auto;
      }
    }

But fails with error:

    .pull-right>.dropdown-menu is undefined on line 189 in file 'dropdowns.less':
    [188]:     .dropdown-menu {
    [189]:       .pull-right > .dropdown-menu();
           ------^
    [190]:     }

**Comment by rytmis** [comment]
It's a caching bug. Selector nodes cached their output CSS, so when comparing the selector for the mixin call with the selector generated for the mixin itself, there was a discrepancy: the former would not be compressed (because why would it, it's for an internal lookup operation) and the latter, due to caching, would be. Removing the caching fixes the issue.

**Comment by ccdiego5** [comment]
Expected ')' but found ' ' on line 20 in file 'mixins/image.less':
 [19]: // spelling of `min--moz-device-pixel-ratio` is intentional.
 [20]: .img-retina(@file-1x; @file-2x; @width-1x; @height-1x) {
       --------------------^
 [21]:   background-image: url("@{file-1x}");
