### ISSUE TITLE
Using a variable in an @import

### ISSUE THREAD

**Issue by iambacon** [dotless/dotless#353]
I may have got it wrong but I was under the impression that this was possible in Less.js version 1.4

    @Utilities-path: "../../Utilities";

    @import "@{Utilities-path}/bacon.less";

This however doesn't work in DotLess v1.4. You receive a File Not Found error.  Should this work?  And it is not in DotLess can we please have this feature.

http://stackoverflow.com/questions/21438937/using-a-variable-in-import-statement-dotless

**Comment by JeffreyArts** [comment]
I miss this feature :(

**Comment by rytmis** [comment]
So do I. Unfortunately, implementing it is non-trivial. At first, I thought it would be a fairly simple matter, which is why my commit above says that it fixes this issue -- except, it only did it for CSS imports. 

Dotless' processing is roughly divided into three stages: parsing, evaluating and output. Currently, as I understand it, dotless implements @import entirely in the parsing stage. This means that variable interpolation _can't_ quite work the way it should, because variable values are only available at a later stage.

Things are slightly better for the simple case of CSS imports, because they are handled by outputting the import node into the parse tree. This means that when that node is evaluated, it can also evaluate the quoted path and things will work nicely.

For LESS imports, the file contents obviously need to be parsed too. Since parsing currently happens as a separate stage that precedes evaluation, having this work means that it's necessary to do a bit of rearranging in dotless' internals -- chiefly, having the parser handy in the evaluation environment and then deferring LESS import parsing to the evaluation stage. I'm working on implementing that now.
