### ISSUE TITLE
Broken @import directives

### ISSUE THREAD

**Issue by tkholmes** [dotless/dotless#378]
The dotless.Compiler.exe throws a null reference exceptions when trying to process LESS files that use @import directives other than (once).

E.G: @import (reference) "some-file-path"; throws an error. 

As do other import options (see http://lesscss.org/features/#import-options).

**Comment by rytmis** [comment]
Near as I can tell, we're talking about a feature that hasn't yet been implemented in dotless (import options). I'm gearing up to do a bugfix release in the next few days that will treat import options as a recognized special case that will result in a parser error instead of a NRE.

I'm planning support for import options in the next feature release.
