### ISSUE TITLE
new variables handling in 1.4.1 crashes dotless

### ISSUE THREAD

**Issue by t1l3r** [dotless/dotless#400]
We wanted to upgrade from **1.3.1** to **1.4.1** but some of our stylesheets caused dotless to trigger a stack overflow. I nailed it to the following simplified code excerpt:

```javascript
@_eox-btn_iconWidth: 17px;
.btn { @iconWidth: @_eox-btn_iconWidth;
	&.big { @iconWidth: 2*@iconWidth;
		&.eox-btn-icon-notext { width: @iconWidth; height: @iconWidth; }
	}
}
```

While there is absolutly **no issue in 1.3.1**, the doubling of the `@iconWidth` is the culprit for the **stack overflow in 1.4.1**.

**Comment by rytmis** [comment]
less.js produces an error with this input: 

Error: Recursive variable definition for @iconWidth

Dotless should at the very least replicate that instead of SO'ing. Technically, there's no reason why it couldn't allow a recursive _re_-definition of a variable, but that would seem to be a break away from the less.js implementation.

**Comment by rytmis** [comment]
... although it looks like the variable hoisting behavior of less.js (see #364) does somewhat conflict with the idea of a recursive re-define.

**Comment by rytmis** [comment]
#413 transforms the stack overflow to a parser error, like it should.
