### ISSUE TITLE
Empty CSS generation at startup 

### ISSUE THREAD

**Issue by chrilith** [dotless/dotless#418]
Hi,

Don't know how to reproduce it effectively but randomly, when I launch my site for the first time, the LESS compilation seems to fail and the rendered bundle line in the HTML code has a ?v= with no data (no hash).

Sometimes the data is here but the document content is empty.

Stopping and restarting the web site seems to fix the problem but not always.

Setting the cache to false in the web.config seems to fix the problem.

Occuring with dotless.1.4.1.0, System.Web.Optimization.Less.1.3.3 and Microsoft.AspNet.Web.Optimization.1.1.3

Seems to be related to this: https://github.com/scott-xu/System.Web.Optimization.Less/issues/21

Thanks !

**Comment by rytmis** [comment]
@chrilith: Here's an easy repro. In Visual Studio, go to your web project's properties. Change the startup URL so that it points to a page that references a LESS bundle. Then add a query string parameter that dotless would turn into an invalid variable, e.g. `?a=b-c`.

Now, for the workaround: in web.config, change your dotless configuration:
    `<dotless  ... disableParameters="true"/>`

and try again. The issue should go away.

There are a couple of things to do here:

- Make S.W.O.Less disable parameter support. It's unlikely that bundle parameters ever make sense as less variables.
- Change dotless to never use the Parameter Decorator in the standalone configuration, only in HTTP Handler mode
- Make dotless handle invalid variables gracefully

**Comment by rytmis** [comment]
Oh, also, note that in order for this to repro, you'll have to be in production mode (`<compilation debug="false" />`), otherwise the LESS processing won't happen in the context of the initial request.

**Comment by rytmis** [comment]
Oh, also: I noticed that ?a=b-c doesn't trigger the issue like I first thought, but ?a=1-b does. See PR #425 for the repro steps, so you can verify that the Web.config setting really does mitigate the issue.
