### ISSUE TITLE
Query string variables overridden in stylesheet

### ISSUE THREAD

**Issue by Supercheez** [dotless/dotless#431]
Would it be possible to allow the query string parameters to override variables in the less files? Currently it seems the only options are:
* not to define the variables in the stylesheets, in which case the stylesheets cannot be compiled independently and there are intellisense errors about undefined variables
* define the variables in the stylesheets, and since the query string parameters are prepended they then get overridden by the variables in the stylesheets

If there were a config option to append the query string parameters instead then this could be combined with disableVariableRedefines to achieve the desired effect.

Thanks!

**Comment by rytmis** [comment]
I'm very much of the opinion that in 1.5, "disableVariableRedefines" will be the default and only variable scoping mode. My rationale for this is twofold: it's in line with less.js and the discussions in the bug reports indicate that the setting name is _very_ confusing to everyone.

Having that as the only variable scoping mode would mean that there would be no further _breaking_ change in moving the qs variables from prepended to appended, so I'm thinking this is a reasonable change to make.

**Comment by Supercheez** [comment]
That's brilliant, thanks - is there a projected release date for 1.5.0?

**Comment by rytmis** [comment]
I'm currently working on #292 and I really really want that fix in the first prerelease build of 1.5, because I want the most risky changes to get the most exposure before pulling the release lever.

Right now, what I've got is a vague, completely unfounded hope of getting the prerelease out during March.  If I manage that, I might be able to work this one in as well.

I'm not making any promises, but if that means I'd get someone to actually test the prerelease for me, it does make me inclined to at least try. ;-)

**Comment by rytmis** [comment]
Welp. I got carried away, finished #292 and went and implemented this one too. 

In case you're interested in testing this feature, the changes are available on nuget.org: https://www.nuget.org/packages/dotless/1.5.0-alpha1.
