### ISSUE TITLE
Mathematically color manipulation now supported anymore?

### ISSUE THREAD

**Issue by oguzhankahyaoglu** [dotless/dotless#496]
I realized a bug I think;

Our front-end developer was using color manipulations like: 
background-color: #333e48 - 20; 
which was resulting in
background-color: #1f2a34;
in our old version (1.3.1). I tested this scenario with v1.5.2-beta4. It does not do any calculations in this beta version. Strict math is enabled, first I thought it can be related with that feature, I used it with paranthesis but didnt worked.

Is this a bug or did you give up an existing feature? 

I searched any issue related with this, but i could not find...

**Comment by rytmis** [comment]
Can you provide the exact steps to reproduce your issue? I tried a simple scenario, and here's what I got (using 1.5.2-beta4):

```
C:\temp\lesstest
λ cat test.less

body {
    background-color: #333e48 - 20;
}

C:\temp\lesstest
λ C:\projects\dotless\build\dotless.Compiler.exe test.less

[Compile]
C:\temp\lesstest\test.less -> C:\temp\lesstest\test.css
[Done in 00:00:00.0974201]

C:\temp\lesstest
λ cat test.css

body {
  background-color: #1f2a34;
}
```

... which is to say, I got the results you were expecting. Now, of course, if you turn on Strict Math, it won't do that, because it won't do any math that isn't enclosed in parens. In Strict Math mode, it needs to look like this:

```less
body {
    background-color: (#333e48 - 20);
}
```

**Comment by oguzhankahyaoglu** [comment]
I think, it got confues with the versions. Today I came to office and tried it with beta4 (strict math enabled) and using paranthesis worked perfectly. Thanks.
