### ISSUE TITLE
Add strong-name

### ISSUE THREAD

**Issue by twenzel** [dotless/dotless#564]
Due to the recommendation by Microsoft (https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/) this library should have a strong-name.

**Comment by rytmis** [comment]
That’s a hard no from me. Strong naming is a pain. What’s the benefit you’re looking to gain?

**Comment by twenzel** [comment]
It‘s the latest recommendation from MS for Open-source projects (See link).
The pain you mentioned is only for .Net Framework, not .Net Core. 
I suggest to apply strong-naming only for netstandard target. 

> Am 16.10.2018 um 09:38 schrieb Lauri Kotilainen <notifications@github.com>:
> 
> That’s a hard no from me. Strong naming is a pain. What’s the benefit you’re looking to gain?
>

**Comment by Tigraine** [comment]
I can see the point Microsoft is trying to make here - but I am also not sure if the hassle with handling the key is really worth the effort (also how would people build their local versions of dotless?)

Since it's only a recommendation and no requirement I'd suggest we wait for someone to actually ask for this and come up with some good reason why they need this. Key distribution/revokation etc really is a non-trivial issue

**Comment by CZEMacLeod** [comment]
I would love to see StrongNamed versions of dotless ([dotless.Core](https://www.nuget.org/packages/dotless.Core/) and [dotless.AspNetHandler](https://www.nuget.org/packages/dotless.AspNetHandler/))

Can I suggest keeping the keys offline and just using them for the build/release process?

You could either use the technique used by EntityFramework to allow building and using the code with the strongname in place without the key [SkipStrongNames](https://github.com/aspnet/EntityFramework6/wiki/Building-the-Runtime) or take the approach of some other libraries by building a normal and StrongNamed version like [Nito.AsyncEx](https://www.nuget.org/packages/Nito.AsyncEx)) and [Nito.AsyncEx.StrongNamed](https://www.nuget.org/packages/Nito.AsyncEx.StrongNamed/)

As long as you will take PR's or release bugfixes relatively quickly; there is no need to anyone else to 'release' a version of dotless and so they wouldn't need the keys. 
If someone needs to work on the code they can test, build and run the code by either bypassing the strongnames or simply creating a fork to build their own dlls without strongnames (maybe even with a different assembly name) and use them instead.

**Comment by CZEMacLeod** [comment]
Sorry - I was using an older build which wasn't signed - I have updated to the latest build which is signed. Perhaps this issue should be closed?

**Comment by Tigraine** [comment]
@twenzel So the new versions of dotless are strongly named? Anything we should be aware for key distribution etc?

@CZEMacLeod Thanks for reporting this. Yes the issue should probably be closed.

**Comment by CZEMacLeod** [comment]
@Tigraine @twenzel I'm confused now. :/
There is strong naming on `dotless.AspNet` and `dotless.Core`
It was part of issue #552 fixed with [Add strong name for dotless.AspNet](https://github.com/dotless/dotless/commit/0d0c4a7317ac38045b08c58e228dca565e93b040) using the key file [dotless-open-source.snk](https://github.com/dotless/dotless/blob/master/src/dotless-open-source.snk)
This was put into release [1.6.3](https://github.com/dotless/dotless/releases/tag/1.6.3)

**Comment by Tigraine** [comment]
That's why I am also confused :)
