### ISSUE TITLE
Compiling a folder of .less files

### ISSUE THREAD

**Issue by peirix** [dotless/dotless#64]
Is it possible to make the compiler run through a folder (with sub folders) of .less files, and compile out .css files in the respective folders?

**Comment by rytmis** [comment]
I don't think this is a good idea to implement directly in dotless. Consider, for instance, a less file that requires variables or mixins defined in another file in order to function, but it doesn't import the defining file itself -- instead, both files are imported by a single master file. Now, compiling all three files separately would result in an error for one of them.

The smart choice, in my opinion, would be to write a PowerShell or bash script (depending on your environment).
